Host: blog.skeptics.xyz
LinksUseHttps: true
MirrorResources: true
EditLink: => "https://github.com/think-mm/blog/edit/dev/input/" + doc.Source.GetRelativeInputPath()
GitHubOwner: think-mm
GitHubName: blog
GitHubToken: => Config.FromSetting<string>("GITHUB_TOKEN")
GitHubBranch: web
